#!/usr/bin/env bash
# Script installs nginx web server

sudo apt-get update -y && \
sudo apt-get install -y nginx

if [ $? -eq 0 ]; then
    echo -e \
    "http {
        root /var/www/school;
        index index.html;

        server {
            listen 80;
            location / {
            }
        }
    }

    events {}" | sudo tee /etc/nginx/nginx.conf > /dev/null

    sudo mkdir -p /var/www/school
    echo "Hello World!" | sudo tee /var/www/school/index.html > /dev/null

    sudo service nginx start
    if [ $? -ne 0 ]; then
        echo "Problem starting nginx"
        exit 1
    else
        echo "Nginx installed and configured successfully."
        exit 0
    fi
else
    echo "Could not install nginx"
    exit 1
fi
