#!/usr/bin/env bash
# uses a Bash script to display the content of the file /etc/passwd.
passwd_file="/etc/passwd"

while IFS=: read -r username password uid gid info homedir shell; do
  echo "Username: $username"
  echo "User ID: $uid"
  echo "Home Directory: $homedir"
done < "$passwd_file"
